import { defineToolcraft } from "@/toolcraft/runtime";

import {
  createPatternSource,
  createDefaultDirectionalPhases,
  createDefaultMosaicSettings,
  createDefaultTriangleSettings,
  defaultPatternGradient,
  defaultOpacityDistribution,
  type PatternSource,
} from "./pattern-model";
import { patternTargets, type PatternVariantValue } from "./pattern-state";
import { defaultShapeImportForm } from "./shapes/import-form";
import type { ShapeVariant } from "./shapes/types";

// The schema must also be loadable by Node-based contract and Playwright
// discovery. Keep its initial source self-contained; the browser catalog uses
// Vite's import.meta.glob and supplies the complete family after startup.
const defaultVariant: ShapeVariant = {
  axis: "weight",
  axisValue: "base",
  fileName: "weight-base__radius-0.svg",
  id: "weight-base__radius-0",
  nominalThicknessPx: 6,
  opacityUnits: { count: 1, mode: "whole-svg" },
  radiusPx: 0,
  svgBody:
    '<path fill-rule="evenodd" clip-rule="evenodd" d="M24 24H0V0H24V24ZM6 6V18H18V6H6Z"/>',
};
const defaultBoldVariant: ShapeVariant = {
  axis: "weight",
  axisValue: "bold",
  fileName: "weight-bold__radius-0.svg",
  id: "weight-bold__radius-0",
  nominalThicknessPx: 8,
  opacityUnits: { count: 1, mode: "whole-svg" },
  radiusPx: 0,
  svgBody:
    '<path fill-rule="evenodd" clip-rule="evenodd" d="M24 24H0V0H24V24ZM8 16H16V8H8V16Z"/>',
};

const defaultSource: PatternSource = {
  ...createPatternSource({
    availableVariants: [defaultVariant, defaultBoldVariant],
    axis: defaultVariant.axis,
    axisValue: defaultVariant.axisValue,
    category: "base",
    familyId: "square",
    familyName: "Square",
    radiusPx: defaultVariant.radiusPx,
    svgBody: defaultVariant.svgBody,
    variantId: defaultVariant.id,
  }),
  id: "source-default-square",
};

const defaultVariantValue: PatternVariantValue = {
  axis: defaultSource.axis,
  axisValue: defaultSource.axisValue,
  familyId: defaultSource.familyId,
  id: defaultSource.variantId,
  opacityUnits: defaultSource.opacityUnits,
  radiusPx: defaultSource.radiusPx,
  svgBody: defaultSource.svgBody,
};

const defaultDirectionalPhases = createDefaultDirectionalPhases(defaultSource.id);
const defaultMosaicSettings = createDefaultMosaicSettings(defaultSource.id);
const defaultTriangleSettings = createDefaultTriangleSettings([defaultSource]);

export const appSchema = defineToolcraft({
  canvas: {
    draggable: true,
    enabled: true,
    size: { height: 199, unit: "px", width: 399 },
    sizing: { mode: "editable-output" },
    upload: false,
  },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            help: {
              defaultValue: null,
              label: false,
              performanceReason: "Static canvas sizing guidance has no renderer cost.",
              performanceRole: "responsiveness",
              target: "ui.canvasSizingHelp",
              type: "canvasSizingHelp",
            },
          },
          title: "Canvas Sizing",
        },
        {
          controls: {
            method: {
              defaultValue: "base-grid",
              description: "Base fills one-size cells, Gradient assigns directional phases, Mosaic combines recursive sizes, and Triangle builds an equilateral lattice.",
              label: "Method",
              options: [
                { label: "Base", value: "base-grid" },
                { label: "Gradient", value: "directional-phases" },
                { label: "Mosaic", value: "multi-size-mosaic" },
                { label: "Triangle", value: "triangle-lattice" },
              ],
              performanceReason: "Switching method changes visible draft controls without rendering until Create or Update commits a snapshot.",
              performanceRole: "workload",
              target: patternTargets.method,
              type: "select",
            },
            distribution: {
              defaultValue: "equal",
              description: "Equal uses uniform probability; Weighted reads each source probability.",
              label: "Base distribution",
              orderRole: "strength",
              performanceReason: "Distribution changes source selection for every Base Grid cell.",
              performanceRole: "workload",
              options: [
                { label: "Equal", value: "equal" },
                { label: "Weighted", value: "weighted" },
              ],
              target: patternTargets.distribution,
              type: "segmented",
              visibleWhen: { equals: "base-grid", target: patternTargets.method },
            },
            angle: {
              defaultValue: 0,
              description: "0° points right; positive angles rotate counterclockwise like Figma.",
              label: "Direction angle",
              max: 359,
              min: 0,
              performanceReason: "Angle rebuilds phase assignment only when a Gradient pattern is committed.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.angle,
              type: "slider",
              unit: "°",
              visibleWhen: { equals: "directional-phases", target: patternTargets.method },
            },
            phases: {
              defaultValue: defaultDirectionalPhases,
              description: "Order phases along the direction, set shares totaling 100%, assign Pattern Shapes, and optionally mix individual cells across each adjacent boundary with Transition Spread.",
              label: false,
              orderRole: "strength",
              performanceReason: "Phase and Transition Spread edits change directional source assignment when a Gradient pattern is committed.",
              performanceRole: "workload",
              target: patternTargets.phases,
              type: "directionalPhases",
              visibleWhen: { equals: "directional-phases", target: patternTargets.method },
            },
            amountMode: {
              defaultValue: defaultMosaicSettings.amountMode,
              description: "Count uses exact tile totals. Coverage requests occupied area and reports the closest representable result.",
              label: "Amount mode",
              orderRole: "strength",
              options: [
                { label: "Count", value: "count" },
                { label: "Coverage", value: "coverage" },
              ],
              performanceReason: "Amount mode changes Mosaic count derivation when a pattern is committed.",
              performanceRole: "workload",
              target: patternTargets.mosaicAmountMode,
              type: "segmented",
              visibleWhen: { equals: "multi-size-mosaic", target: patternTargets.method },
            },
            config: {
              defaultValue: {
                clusters: defaultMosaicSettings.clusters,
                levels: defaultMosaicSettings.levels,
              },
              description: "Assign Pattern Shapes to recursive sizes, distribute them among clusters, and tune each cluster silhouette.",
              label: false,
              orderRole: "strength",
              performanceReason: "Mosaic recipe changes size derivation, packing, source selection, and final SVG cells when committed.",
              performanceRole: "workload",
              target: patternTargets.mosaicConfig,
              type: "mosaicConfig",
              visibleWhen: { equals: "multi-size-mosaic", target: patternTargets.method },
            },
            triangleConfig: {
              defaultValue: defaultTriangleSettings,
              description: "Build each rectangular element from alternating Full triangles and two automatic Half caps, then assign compatible source pools.",
              label: false,
              orderRole: "strength",
              performanceReason: "Triangle topology and pool edits rebuild the committed lattice.",
              performanceRole: "workload",
              target: patternTargets.triangleConfig,
              type: "triangleConfig",
              visibleWhen: { equals: "triangle-lattice", target: patternTargets.method },
            },
          },
          title: "Pattern Method",
        },
        {
          controls: {
            library: {
              defaultValue: defaultSource.id,
              description:
                "Browse base and complex families, choose a weight or form and radius variant, then add it to the pattern.",
              label: false,
              performanceReason:
                "Catalog browsing previews hundreds of local vector variants without changing the canvas workload.",
              performanceRole: "responsiveness",
              target: patternTargets.selectedSourceId,
              type: "shapeLibrary",
            },
          },
          title: "Shape Library",
        },
        {
          controls: {
            upload: {
              accept: ".svg,image/svg+xml",
              assetKind: "file",
              defaultValue: null,
              multiple: true,
              description: "Choose one safe 24×24 SVG. Any filename works; recognized catalog names only prefill variant metadata.",
              label: "SVG file",
              performanceReason: "The selected local SVG is validated only when import is applied.",
              performanceRole: "responsiveness",
              target: "library.upload",
              type: "fileDrop",
            },
          },
          title: "SVG file",
        },
        {
          controls: {
            details: {
              defaultValue: defaultShapeImportForm,
              label: false,
              performanceReason: "Validated metadata and one SVG write do not rebuild the pattern preview.",
              performanceRole: "responsiveness",
              target: "library.importForm",
              type: "shapeImportDetails",
            },
          },
          title: "Import Details",
        },
        {
          controls: {
            sources: {
              defaultValue: [defaultSource],
              description:
                "Select, reorder, remove, and normalize reusable shape sources shared by every pattern method.",
              label: false,
              performanceReason:
                "Changing source count or order rebuilds deterministic cell assignments and vector output.",
              performanceRole: "workload",
              target: patternTargets.sources,
              type: "patternSources",
            },
          },
          title: "Pattern Shapes",
        },
        {
          controls: {
            empty: {
              defaultValue: null,
              label: false,
              performanceReason: "The empty selection message has no renderer cost.",
              performanceRole: "responsiveness",
              target: "ui.selectedShapeEmpty",
              type: "emptySelection",
              visibleWhen: { equals: "", target: patternTargets.selectedSourceId },
            },
            variant: {
              defaultValue: defaultVariantValue,
              description: "Choose an available semantic weight or form, then its radius variant.",
              label: "Variant",
              performanceReason: "Variant changes replace vector geometry across matching cells.",
              performanceRole: "responsiveness",
              target: patternTargets.variant,
              type: "shapeVariant",
              visibleWhen: { notEquals: "", target: patternTargets.selectedSourceId },
            },
            frameWidth: {
              defaultValue: 24,
              label: "Frame width",
              max: 256,
              min: 1,
              performanceReason: "Frame width changes the grid cell size and total vector extent.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.frameWidth,
              type: "slider",
              unit: "px",
              visibleWhen: { notEquals: "", target: patternTargets.selectedSourceId },
            },
            frameHeight: {
              defaultValue: 24,
              label: "Frame height",
              max: 256,
              min: 1,
              performanceReason: "Frame height changes the grid cell size and total vector extent.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.frameHeight,
              type: "slider",
              unit: "px",
              visibleWhen: { notEquals: "", target: patternTargets.selectedSourceId },
            },
            scale: {
              defaultValue: 100,
              description: "Scales the vector independently inside its grid-cell frame.",
              label: "Shape scale",
              max: 200,
              min: 5,
              performanceReason: "Shape scale updates every occurrence of the selected source.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.scale,
              type: "slider",
              unit: "%",
              visibleWhen: { notEquals: "", target: patternTargets.selectedSourceId },
            },
            rotation: {
              defaultValue: 0,
              label: "Source rotation",
              max: 360,
              min: 0,
              performanceReason: "Rotation updates every occurrence of the selected source.",
              performanceRole: "responsiveness",
              step: 15,
              target: patternTargets.rotation,
              type: "slider",
              visibleWhen: { notEquals: "", target: patternTargets.selectedSourceId },
              unit: "°",
            },
            weight: {
              defaultValue: 1,
              description: "Relative occurrence frequency when distribution is Weighted.",
              label: "Probability",
              max: 100,
              min: 1,
              performanceReason: "Probability changes deterministic weighted cell assignment.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.weight,
              type: "slider",
              visibleWhen: { notEquals: "", target: patternTargets.selectedSourceId },
            },
          },
          title: "Selected Shape",
        },
        {
          controls: {
            fillMode: {
              defaultValue: "solid",
              label: "Fill",
              options: [
                { label: "Solid", value: "solid" },
                { label: "Gradient", value: "gradient" },
              ],
              performanceReason: "Fill mode switches between the existing solid and gradient definitions.",
              performanceRole: "responsiveness",
              target: patternTargets.fillMode,
              type: "segmented",
              visibleWhen: { notEquals: "", target: patternTargets.selectedSourceId },
            },
            color: {
              defaultValue: "#FFFFFF",
              label: "Source color",
              performanceReason: "Color updates the SVG fill without changing cell count.",
              performanceRole: "responsiveness",
              target: patternTargets.color,
              type: "color",
              visibleWhen: { equals: "solid", target: patternTargets.fillMode },
            },
            gradient: {
              defaultValue: defaultPatternGradient,
              description: "Edit type, color stops, opacity, angle, and gradient origin.",
              label: "Gradient",
              performanceReason: "Gradient edits update SVG definitions without changing cell count.",
              performanceRole: "responsiveness",
              target: patternTargets.gradient,
              type: "gradient",
              visibleWhen: { equals: "gradient", target: patternTargets.fillMode },
            },
            opacity: {
              defaultValue: 100,
              label: "Source opacity",
              max: 100,
              min: 0,
              performanceReason: "Opacity updates every occurrence of the selected source.",
              performanceRole: "responsiveness",
              step: 1,
              target: patternTargets.opacity,
              type: "slider",
              unit: "%",
              visibleWhen: { notEquals: "", target: patternTargets.selectedSourceId },
            },
            empty: {
              defaultValue: null,
              label: false,
              orderRole: "detail",
              performanceReason: "The empty selection message has no renderer cost.",
              performanceRole: "responsiveness",
              target: "ui.shapeFillEmpty",
              type: "emptySelection",
              visibleWhen: { equals: "", target: patternTargets.selectedSourceId },
            },
          },
          title: "Shape Fill",
        },
        {
          controls: {
            rows: {
              defaultValue: 8,
              label: "Rows",
              markerCount: 8,
              max: 64,
              min: 1,
              performanceReason: "Rows directly multiply the number of rendered vector cells.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.rows,
              type: "slider",
            },
            columns: {
              defaultValue: 16,
              label: "Columns",
              markerCount: 8,
              max: 64,
              min: 1,
              performanceReason: "Columns directly multiply the number of rendered vector cells.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.columns,
              type: "slider",
            },
            gap: {
              defaultValue: 1,
              label: "Grid gap",
              max: 48,
              min: 0,
              performanceReason: "Gap changes output extent while preserving the number of cells.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.gap,
              type: "slider",
              unit: "px",
            },
            seed: {
              defaultValue: 42,
              description: "The same sources, settings, and seed always reproduce the same pattern.",
              label: "Seed",
              max: 99999,
              min: 0,
              performanceReason: "Seed regenerates all deterministic source assignments.",
              performanceRole: "workload",
              step: 1,
              target: patternTargets.seed,
              type: "slider",
            },
            autoFit: {
              defaultValue: true,
              description: "Resize the editable output to the exact grid bounds after changes.",
              label: "Auto-fit output",
              orderRole: "strength",
              performanceReason: "Auto-fit issues one canvas-size update after a valid grid change.",
              performanceRole: "workload",
              target: patternTargets.autoFit,
              type: "switch",
            },
            regenerate: {
              actions: [
                {
                  icon: "shuffle",
                  label: "New seed",
                  value: "regenerate",
                },
              ],
              label: false,
              orderRole: "strength",
              performanceReason: "New seed rebuilds deterministic source selection for every cell.",
              performanceRole: "responsiveness",
              target: "actions.regenerate",
              type: "actions",
            },
          },
          title: "Grid",
        },
        {
          controls: {
            opacityDistribution: {
              defaultValue: defaultOpacityDistribution,
              description: "Apply deterministic weighted opacity to each cell as a whole or independently to annotated elements inside composite shapes.",
              label: false,
              orderRole: "strength",
              performanceReason: "Changing the appearance recipe rebuilds only used opacity signatures when the pattern is committed.",
              performanceRole: "workload",
              target: patternTargets.opacityDistribution,
              type: "opacityDistribution",
            },
          },
          title: "Opacity Distribution",
        },
        {
          controls: {
            patternName: {
              commitMode: "setting",
              defaultValue: "Pattern 1",
              description: "Names the next pattern or the active pattern when Update pattern is used.",
              label: "Pattern name",
              performanceReason: "The pattern name changes metadata only.",
              performanceRole: "responsiveness",
              target: patternTargets.patternName,
              type: "text",
            },
            patternActions: {
              actions: [
                {
                  icon: "wand-sparkles",
                  label: "Create pattern",
                  value: "create-pattern",
                },
                {
                  icon: "rotate-ccw",
                  label: "Update pattern",
                  value: "update-pattern",
                },
              ],
              description: "Create always adds a new history entry. Update overwrites the active entry.",
              label: false,
              orderRole: "strength",
              performanceReason: "Creating or updating validates the draft and commits one deterministic snapshot.",
              performanceRole: "responsiveness",
              target: "actions.pattern",
              type: "actions",
            },
          },
          title: "Pattern Output",
        },
        {
          controls: {
            history: {
              defaultValue: [],
              description: "Select the visible pattern, load a snapshot for editing, rename it, or delete it.",
              label: false,
              performanceReason: "Selecting a history entry swaps one immutable pattern snapshot.",
              performanceRole: "workload",
              target: patternTargets.history,
              type: "patternHistory",
            },
          },
          title: "Pattern History",
        },
        {
          controls: {
            includeBackground: {
              defaultValue: true,
              description: "Controls live preview and PNG/JPG background visibility.",
              label: "Include",
              performanceReason: "Background inclusion toggles a single SVG rectangle.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            background: {
              defaultValue: "#D9DCE4",
              label: false,
              performanceReason: "Background color updates a single SVG rectangle.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["includeBackground", "background"], layout: "inline" },
          ],
          title: "Background",
        },
        {
          controls: {
            fileName: {
              commitMode: "setting",
              defaultValue: "sanchez-pattern",
              description: "Used by SVG, PNG, and JPG downloads. The extension is added automatically.",
              label: "File name",
              performanceReason: "The filename is read only when an export starts.",
              performanceRole: "responsiveness",
              target: "export.fileName",
              type: "text",
            },
            imageFormat: {
              defaultValue: "png",
              description: "Raster format used only by Export Image. SVG export stays vector.",
              label: "Image format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              performanceReason: "Format is read only when the image export action runs.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            imageResolution: {
              defaultValue: "4k",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              performanceReason: "Resolution is read only when the image export action runs.",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
            },
            help: {
              defaultValue: null,
              label: false,
              performanceReason: "Static export guidance has no renderer cost.",
              performanceRole: "responsiveness",
              target: "ui.exportHelp",
              type: "exportHelp",
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["imageFormat", "imageResolution"], layout: "inline" },
          ],
          title: "Image Export",
        },
        {
          actionGroup: "primary",
          controls: {
            outputActions: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export SVG",
                  value: "export-svg",
                  variant: "secondary",
                },
                {
                  icon: "upload-simple",
                  label: "Export Image",
                  value: "export-image",
                  variant: "secondary",
                },
              ],
              label: false,
              target: "actions.output",
              type: "panelActions",
            },
          },
          title: "Output",
        },
      ],
      title: "Pattern Creator",
    },
    layers: false,
    timeline: false,
  },
  persistence: {
    include: ["values", "canvas", "panels"],
    key: "toolcraft:sanchez-pattern:state:v1",
    storage: "localStorage",
    version: 1,
  },
  settingsTransfer: "auto",
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
